name: Check Commits

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Run bot script
        run: |
          export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export CHANNEL_ID=${{ secrets.CHANNEL_ID }}
          npm run build && npm run start